name: Telegram Send Message
description: Sends a message to a Telegram chat using a bot.
inputs:
  message:
    description: "The message to send"
    required: true
    default: "Hello from GitHub Actions!"
runs:
  using: "composite"
  steps:
    - name: Send Telegram Message
      shell: bash
      run: |
        curl -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
        -d "chat_id=${{ secrets.TG_CHAT_ID }}" \
        -d "text=${{ inputs.message }}"
